# Generated by Django 4.2.5 on 2023-09-09 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atividadeCrud', '0002_compras_comprador_alter_pedidos_pagamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente', to='atividadeCrud.usuarios'),
        ),
    ]
