# Generated by Django 4.2.5 on 2023-09-09 21:45

import atividadeCrud.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividadeCrud', '0003_alter_clientes_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='desc',
            field=models.CharField(max_length=500, validators=[django.core.validators.MinLengthValidator(10, 'Descrição precisa ter ao menos 10 caracteres.'), django.core.validators.MaxLengthValidator(500, 'Descrição pode ter ao máximo 50 caracteres.')]),
        ),
        migrations.AlterField(
            model_name='categorias',
            name='nome',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2, 'Nome precisa ter ao menos 2 caracteres.'), django.core.validators.MaxLengthValidator(50, 'Nome pode ter ao máximo 50 caracteres.')]),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='datanasc',
            field=models.DateField(validators=[atividadeCrud.validators.data_menor_atual]),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nome',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2, 'Nome precisa ter ao menos 2 caracteres.'), django.core.validators.MaxLengthValidator(100, 'Nome pode ter ao máximo 100 caracteres.')]),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='telefone',
            field=models.CharField(max_length=15, validators=[atividadeCrud.validators.numero('Telefone'), django.core.validators.MinLengthValidator(8, 'Telefone precisa ter ao menos 8 caracteres.'), django.core.validators.MaxLengthValidator(15, 'Telefone pode ter ao máximo 100 caracteres.')]),
        ),
        migrations.AlterField(
            model_name='compras',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, 'Preço deve ser maior que 0.')]),
        ),
        migrations.AlterField(
            model_name='compras',
            name='quantidade',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Quantidade deve ser maior que 0.')]),
        ),
        migrations.AlterField(
            model_name='enderecos',
            name='bairro',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2, 'Bairro precisa ter ao menos 2 caracteres.'), django.core.validators.MaxLengthValidator(50, 'Bairro pode ter ao máximo 50 caracteres.')]),
        ),
        migrations.AlterField(
            model_name='enderecos',
            name='cep',
            field=models.CharField(max_length=8, validators=[atividadeCrud.validators.numero('Cep'), django.core.validators.MinLengthValidator(8, 'Cep precisa ter 8 caracteres.')]),
        ),
        migrations.AlterField(
            model_name='enderecos',
            name='cidade',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2, 'Cidade precisa ter ao menos 2 caracteres.'), django.core.validators.MaxLengthValidator(50, 'Cidade pode ter ao máximo 50 caracteres.')]),
        ),
        migrations.AlterField(
            model_name='enderecos',
            name='estado',
            field=models.CharField(max_length=2, validators=[django.core.validators.MinLengthValidator(2, 'Estado precisa ter 2 caracteres.')]),
        ),
        migrations.AlterField(
            model_name='enderecos',
            name='numero',
            field=models.CharField(max_length=10, validators=[atividadeCrud.validators.numero('Número'), django.core.validators.MaxLengthValidator(10, 'Número precisa ter no máximo 10 caracteres.')]),
        ),
        migrations.AlterField(
            model_name='enderecos',
            name='rua',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2, 'Rua precisa ter ao menos 2 caracteres.'), django.core.validators.MaxLengthValidator(100, 'Rua pode ter ao máximo 100 caracteres.')]),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.MinLengthValidator(5, 'Endereço precisa ter ao menos 5 caracteres.'), django.core.validators.MaxLengthValidator(200, 'Endereço pode ter ao máximo 200 caracteres.')]),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='endereco',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='nome',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2, 'Nome precisa ter ao menos 2 caracteres.'), django.core.validators.MaxLengthValidator(100, 'Nome pode ter ao máximo 100 caracteres.')]),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='telefone',
            field=models.CharField(max_length=15, validators=[atividadeCrud.validators.numero('Telefone'), django.core.validators.MinLengthValidator(8, 'Telefone precisa ter ao menos 8 caracteres.'), django.core.validators.MaxLengthValidator(15, 'Telefone pode ter ao máximo 100 caracteres.')]),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='cargo',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2, 'Cargo precisa ter ao menos 2 caracteres.'), django.core.validators.MaxLengthValidator(50, 'Cargo pode ter ao máximo 50 caracteres.')]),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='nome',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2, 'Nome precisa ter ao menos 2 caracteres.'), django.core.validators.MaxLengthValidator(100, 'Nome pode ter ao máximo 100 caracteres.')]),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='telefone',
            field=models.CharField(max_length=15, validators=[atividadeCrud.validators.numero('Telefone'), django.core.validators.MinLengthValidator(8, 'Telefone precisa ter ao menos 8 caracteres.'), django.core.validators.MaxLengthValidator(15, 'Telefone pode ter ao máximo 100 caracteres.')]),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
