# Generated by Django 4.2.5 on 2023-09-09 22:01

import atividadeCrud.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividadeCrud', '0004_alter_categorias_desc_alter_categorias_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamentos',
            name='data',
            field=models.DateField(validators=[atividadeCrud.validators.data_menor_atual]),
        ),
        migrations.AlterField(
            model_name='pagamentos',
            name='tipo',
            field=models.CharField(max_length=50, validators=[atividadeCrud.validators.EscolhaValidator(['Cartão de crédito', 'Boleto', 'Transferência bancária'])]),
        ),
        migrations.AlterField(
            model_name='pagamentos',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, 'Valor deve ser maior que 0.')]),
        ),
    ]
