# Generated by Django 4.2.5 on 2023-09-10 01:01

import atividadeCrud.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividadeCrud', '0006_alter_pedidos_data_alter_pedidos_data_entrega_real_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='data',
            field=models.DateField(validators=[atividadeCrud.validators.data_menor_igual_atual]),
        ),
    ]
