# Generated by Django 4.2.5 on 2023-09-10 01:04

import atividadeCrud.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividadeCrud', '0007_alter_pedidos_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='data',
            field=models.DateTimeField(validators=[atividadeCrud.validators.data_menor_igual_atual]),
        ),
    ]
