# Generated by Django 4.2.5 on 2023-09-10 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividadeCrud', '0008_alter_pedidos_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='data',
            field=models.DateField(),
        ),
    ]
