# Generated by Django 4.2.5 on 2023-09-10 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividadeCrud', '0011_alter_pedidos_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
