# Generated by Django 4.2.5 on 2023-09-10 01:43

import atividadeCrud.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividadeCrud', '0012_alter_pedidos_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='telefone',
            field=models.CharField(max_length=15, validators=[atividadeCrud.validators.numero('Telefone'), django.core.validators.MinLengthValidator(8, 'Telefone precisa ter ao menos 8 caracteres.'), django.core.validators.MaxLengthValidator(15, 'Telefone pode ter ao máximo 15 caracteres.')]),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='desc',
            field=models.CharField(max_length=1000, validators=[django.core.validators.MinLengthValidator(10, 'Descrição precisa ter ao menos 10 caracteres.'), django.core.validators.MaxLengthValidator(500, 'Descrição pode ter ao máximo 50 caracteres.')]),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='estoque',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0, 'Estoque não pode ser menor que 0.')]),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='nome',
            field=models.CharField(max_length=1000, validators=[django.core.validators.MinLengthValidator(2, 'Nome precisa ter ao menos 2 caracteres.'), django.core.validators.MaxLengthValidator(100, 'Nome pode ter ao máximo 100 caracteres.')]),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, 'Preço deve ser maior que 0.')]),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nome',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2, 'Nome precisa ter ao menos 2 caracteres.'), django.core.validators.MaxLengthValidator(100, 'Nome pode ter ao máximo 100 caracteres.')]),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='senha',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(8, 'Senha precisa ter ao menos 8 caracteres.'), django.core.validators.MaxLengthValidator(50, 'Senha pode ter ao máximo 50 caracteres.')]),
        ),
    ]
