# Generated by Django 4.1.7 on 2023-09-11 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atividadeCrud', '0013_alter_clientes_telefone_alter_produtos_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='data_compra',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='itens_de_pedidos',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='atividadeCrud.produtos'),
        ),
    ]
